routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=>true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('verified');

Route::namespace('App\Http\Controllers\Admin')->prefix('admin')->middleware(['auth','auth.admin','verified'])->name('admin.')->group(function(){
    Route::resource('/users','UserController',['except'=>['show','create','store']]);
    Route::resource('/cvmenagement','CvMenagementController',['except'=>['destroy','create','store','edit','update','create','store','show']]);
    Route::get('/cvblade/{id}','CvMenagementController@cvblade')->name('cvmenagement.cvblade');

});

Route::namespace('App\Http\Controllers\CV')->middleware('auth','verified')->group(function(){
    Route::get('/index', 'CvController@index')->name('cv.index');
    Route::get('/create' ,'CvController@create')->name('cv.create');
    Route::post('/create', 'CvController@store')->name("cv.store");
    Route::get('/edit', 'CvController@edit')->name("cv.edit");
    Route::delete('/edit','CvController@destroy')->name('cv.destroy');
    Route::post('/edit/', 'CvController@update')->name("cv.update");
    Route::post('/edit/', 'CvController@update')->name("cv.update");


});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles (){
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles){
        return null !== $this->roles()->whereIn('name',$roles)->first();
    }

    public function hasAnyRole($role){
        return null !== $this->roles()->where('name',$role)->first();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index')->with('users',User::paginate(10));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->id==$id){
            return redirect()->route('admin.users.index')->with('warning','You are not allowed to edit your self');
        }

        return view('admin.users.edit')->with(['user'=>User::find($id),'roles'=>Role::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::user()->id==$id){
            return redirect()->route('admin.users.index')->with('warning','You are not allowed to edit your self');
        }
        $user = User::find ($id);
        $user -> roles() -> sync($request->roles);
        return redirect()->route('admin.users.index')->with('success','Edited successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->id==$id){
            return redirect()->route('admin.users.index')->with('warning','You are not allowed to delete your self');
        }
        $user = User::find($id);
        if ($user) {
            $user->roles()->detach();
            $user->delete();
            return redirect()->route('admin.users.index')->with('success','Deleted Successfully');
        }
        return redirect()->route('admin.users.index')->with('success','User can not be Deleted');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Edit '.$user->name) }}</div>

                    <div class="card-body">
                        <form action="{{route('admin.users.update',['user'=>$user->id])}}" method="POST">
                            @csrf
                            {{method_field('PUT')}}
                            @foreach($roles as $role)
                            <div class="form-check">
                                <input type="checkbox" name="roles[]" value="{{$role->id}}"
                                    {{$user->hasAnyRole($role->name)?'checked':''}}>
                                <label>{{$role->name}}</label>
                            </div>
                            @endforeach
                            <button type="submit" class="btn btn-primary">
                                Update
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Manage Users') }}</div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Role</th>
                                <th scope="col">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th>{{$user->name}}</th>
                                    <th>{{$user->email}}</th>
                                    <th>{{implode(', ',$user->roles()->get()->pluck('name')->toArray())}}</th>
                                    <th>
                                        <a href="{{route('admin.users.edit',$user->id)}}" class="float-left">
                                            <button type="button" class="btn btn-primary btn-sm">Edit</button>
                                        </a>
                                        <form action="{{route('admin.users.destroy',$user->id)}}" method="POST">
                                            @csrf
                                            {{method_field('DELETE')}}
                                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </th>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{$users->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection